services:
  app:
    build:
      context: .
      args:
        - PORT=8080
    env_file: .env.docker_local
    ports:
      - 8080:8080

  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=shopping
      - MYSQL_USER=moovup
      - MYSQL_PASSWORD=moovup
    ports:
      - 3306:3306
    volumes:
      # Create tables
      - ./db_migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
